In [1]:
import numpy as np
import tqdm


In [2]:
def p(x, sigma, N=10):
    p_ = 0
    for i in tqdm.trange(-N, N + 1):
        p_ += np.exp(-(x + 2 * np.pi * i) ** 2 / 2 / sigma ** 2)
    return p_


def grad(x, sigma, N=10):
    p_ = 0
    for i in tqdm.trange(-N, N + 1):
        p_ += (x + 2 * np.pi * i) / sigma ** 2 * np.exp(-(x + 2 * np.pi * i) ** 2 / 2 / sigma ** 2)
    return p_

In [3]:
X_MIN, X_N = 1e-5, 5  # relative to pi
SIGMA_MIN, SIGMA_MAX, SIGMA_N = 3e-3, 2, 5  # relative to pi

In [6]:
x = np.linspace(-6, -1, 6)
sigma =np.linspace(2, 12, 6) 

In [7]:
x

array([-6., -5., -4., -3., -2., -1.])

In [8]:
p_ = p(x, sigma[:, None], N=100)
score_ = grad(x, sigma[:, None], N=100) / p_

100%|██████████| 201/201 [00:00<00:00, 28801.72it/s]


In [9]:
score_

array([[ 6.05730143e-02,  2.41849690e-01,  2.47292231e-01,
        -5.16214655e-02, -2.76353830e-01, -1.99815564e-01],
       [ 1.87346226e-04,  6.43244095e-04,  5.07980681e-04,
        -9.47439074e-05, -6.10240990e-04, -5.64359554e-04],
       [ 8.51098452e-09,  2.92087943e-08,  2.30521738e-08,
        -4.29850986e-09, -2.76971631e-08, -2.56311717e-08],
       [ 7.07667135e-15,  2.42861474e-14,  1.91625137e-14,
        -3.57381024e-15, -2.30290050e-14, -2.13088830e-14],
       [ 5.94668721e-18,  3.40868529e-18,  5.84240296e-18,
        -7.57091989e-18,  9.61344074e-18, -2.62786252e-18],
       [ 3.14902572e-18, -4.83384200e-19,  5.99473034e-19,
        -4.37547521e-18,  5.66237703e-18,  6.80714086e-18]])

In [10]:
x = (x + np.pi) % (2 * np.pi) - np.pi
sign = np.sign(x)
x = np.log(np.abs(x) / np.pi)
x = (x - np.log(X_MIN)) / (0 - np.log(X_MIN)) * X_N
x = np.round(np.clip(x, 0, X_N)).astype(int)
sigma = np.log(sigma / np.pi)
sigma = (sigma - np.log(SIGMA_MIN)) / (np.log(SIGMA_MAX) - np.log(SIGMA_MIN)) * SIGMA_N
sigma = np.round(np.clip(sigma, 0, SIGMA_N)).astype(int)


In [11]:
x

array([4, 5, 5, 5, 5, 5])

In [12]:
sigma

array([4, 5, 5, 5, 5, 5])

In [13]:
sign

array([ 1.,  1.,  1., -1., -1., -1.])

In [17]:
ret=-sign * score_[sigma, x]

In [19]:
ret

array([-9.61344074e-18, -6.80714086e-18, -6.80714086e-18,  6.80714086e-18,
        6.80714086e-18,  6.80714086e-18])

In [21]:
ret**2

array([9.24182429e-35, 4.63371667e-35, 4.63371667e-35, 4.63371667e-35,
       4.63371667e-35, 4.63371667e-35])

In [20]:
(ret ** 2).mean(0)

5.40173460841444e-35

In [16]:
score_[[4,4,4,4,4],[4,4,4,4,4]]

array([9.61344074e-18, 9.61344074e-18, 9.61344074e-18, 9.61344074e-18,
       9.61344074e-18])

In [59]:
sign = np.sign(x)
x = np.log(np.abs(x) / np.pi)
x

array([-2.40638369, -0.89538438, -0.31915835, -0.0461176 , -0.45158271,
       -1.14472989])

In [60]:
x = (x - np.log(X_MIN)) / (0 - np.log(X_MIN)) * X_N
x

array([3.95492084, 4.61113951, 4.86139129, 4.97997138, 4.80388012,
       4.50285013])

In [62]:
np.clip(x, 0, X_N)

array([3.95492084, 4.61113951, 4.86139129, 4.97997138, 4.80388012,
       4.50285013])

In [61]:
np.round(np.clip(x, 0, X_N)).astype(int)

array([4, 5, 5, 5, 5, 5])

In [35]:
x=12
X_MIN=5
X_N=12

In [36]:
(x - np.log(X_MIN)) / (0 - np.log(X_MIN)) * X_N

-77.47223057658411

In [7]:
sigma2.shape

(6,)

In [15]:
sigma2[None]

array([[ 2.,  4.,  6.,  8., 10., 12.]])

In [19]:
sigma=sigma2[None].repeat(10, 0).flatten()

In [31]:
out = sigma[:3] * np.random.randn(*sigma[:3].shape)
print(out)

out = (out + np.pi) % (2 * np.pi) - np.pi
print(out)


[ 2.57773054 -4.27561362 -1.62834422]
[ 2.57773054  2.00757169 -1.62834422]


In [27]:
np.random.randn(*sigma.shape).shape

(60,)

In [25]:
sigma=sigma[:, None]

In [28]:
p_ = 0
p_ += np.exp(-(x + 2 * np.pi * -2) ** 2 / 2 / sigma ** 2)


In [30]:
p_/p_

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [2]:
import math, os, torch, yaml
torch.multiprocessing.set_sharing_strategy('file_system')
import numpy as np
from rdkit import RDLogger
import json
import torch


In [3]:
train_loader=torch.load("train_loader.pt")

In [13]:
train_loader.dataset[0].mol.GetNumConformers()

1

In [44]:
split

array([array([ 18599, 122344,   6349, ...,   3518, 122516,  35788], dtype=int64),
       array([118643,  22749,  67259, ...,  86870,  24420,  98744], dtype=int64),
       array([ 55589,  34538, 107691, ..., 107540, 119440,  45002], dtype=int64)],
      dtype=object)

In [49]:
split[0]=np.random.choice(split[0],100)

In [51]:
np.save("data/QM9/split.npy",split)